### ISSUE TITLE
スキル書関連バグ

### ISSUE THREAD

**Issue by aera-ngmansion** [Isaac45132/FE8N#2]
ngmansion#94 
以下引用

> いまの8Nとうちってスキルの仕様違ったと思うんですが大丈夫ですかね？
> 
> そのまま当ててみたら、スキルの書は使えるけど表示はされない＆解除M仕様すると
> 以下画像でフリーズみたいになっちゃったのです。。
> https://gyazo.com/b373ba88e461f07213f5a1297fed78fb
> 
> _Originally posted by @Isaac45132 in https://github.com/ngmansion/FE8N/issues/94#issuecomment-855958782_
>

**Comment by aera-ngmansion** [comment]
d41cb9b1b72ca64091a822e4ee7739eb47b7eba4
af55e084af9c286daeedfb844534406e4c5bbc0b
75287bc77a27635bbaa96d797c4b1bcdd8abd998

**Comment by aera-ngmansion** [comment]
静的チェックだとやはり問題なく見えるが・・・さて・・・

**Comment by Isaac45132** [comment]
なんかEAが１つエラー吐いててそれ直したら正常になりました。
CombatArtsのEAの146行目をPOIN 0にしました。

**Comment by aera-ngmansion** [comment]
関係ない変更で解決したようなのでclose
